apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: duvansang/library-management-backend:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:sqlserver://minio:1433;databaseName=library_db"
            # ... các biến môi trường khác nếu cần

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort # hoặc LoadBalancer nếu chạy cloud
  selector:
    app: backend
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081 # Tùy chọn, nếu muốn truy cập từ ngoài